app/Models/Offer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace freelancerzy.Models
{
    public partial class Offer
    {
        public Offer()
        {
            OfferReports = new HashSet<OfferReport>();
        }
        public int Offerid { get; set; }
        public int UserId { get; set; }
        [Display(Name = "Kategoria")]
        public int CategoryId { get; set; }
        [MaxLength(40, ErrorMessage = "Tytuł może mieć maksymalnie 40 znaków")]
        [Required(ErrorMessage = "Tytuł jest obowiązkowy")]
        [Display(Name = "Tytuł")]
        public string Title { get; set; }
        [MaxLength(1500, ErrorMessage = "Opis może mieć maksymalnie 1500 znaków")]
        [Display(Name = "Opis")]
        public string Description { get; set; }
        [Display(Name = "Data utworzenia")] // nie do edycji
        public DateTime CreationDate { get; set; }
        [Display(Name = "Data ostatniej zmiany")] //Też nie do edycji chyba
        public DateTime? LastModificationDate { get; set; }
        [Display(Name = "Data wygaśnięcia")]
        public DateTime ExpirationDate { get; set; }
        [Display(Name = "Ilość wyświetleń")]
        public int ViewCounter { get; set; }

        public bool IsReported { get; set; }
        public int status { get; set; }

        [Display(Name = "Stawka")]
        [DataType(DataType.Currency)]
        //TODO: zrobić coś żeby ładnie wyświetlało z dwoma miejscami po przecinku
        public decimal? Wage { get; set; }
        [NotMapped]
        [RegularExpression(@"^([0-9]*)([.,]*)([0-9]\d{0,1})$", ErrorMessage = "Zły format")]
        [Display(Name = "Stawka")]
        public string WageValue { get; set; }
        public virtual Category Category { get; set; }
        public virtual PageUser User { get; set; }
        public virtual ICollection<OfferReport> OfferReports { get; set; }
    }
}

app/Controllers/OffersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using freelancerzy.Models;
using Microsoft.AspNetCore.Authorization;
using NinjaNye.SearchExtensions;
using System.Collections;

namespace freelancerzy.Controllers
{
    public class OffersController : Controller
    {
        private readonly cb2020freedbContext _context;

        public OffersController(cb2020freedbContext context)
        {
            _context = context;
        }

        #region Admin - oferty zgłoszone

        [HttpGet]
        [Authorize(Roles = "administrator", AuthenticationSchemes = "CookieAuthentication")]
        public IActionResult ReportedOffers()
        {
            return View();
        }

        [HttpGet]
        [Authorize(Roles = "administrator", AuthenticationSchemes = "CookieAuthentication")]
        public async Task<IActionResult> ReportedOffersListPartial(int? pageNumber, string order)
        {
            var Offers = SortedList(order);
            var reportedOffers = Offers.Where(o => o.IsReported == true).Include(o => o.OfferReports);
            int pageSize = 15;
            return PartialView("_ReportedOfferList", await PaginatedList<Offer>.CreateAsync(reportedOffers, pageNumber ?? 1, pageSize));
        }

        [HttpGet]
        [Authorize(Roles = "administrator", AuthenticationSchemes = "CookieAuthentication")]
        public async Task<IActionResult> ReportedDetails(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var offer = await _context.Offer
                .Include(o => o.Category)
                .Include(o => o.User)
                .Include(o => o.OfferReports)
                .FirstOrDefaultAsync(m => m.Offerid == id);

            var reports = offer.OfferReports.Where(r => r.IsActive == true).ToList();

            foreach (var report in reports)
            {
                report.OfferReportReason = await _context.OfferReportReason.FirstOrDefaultAsync(ors => ors.ReasonId == report.ReasonId);
            }

            offer.OfferReports = reports;

            if (offer == null)
            {
                return NotFound();
            }

            return View(offer);
        }

        [HttpDelete]
        [Authorize(Roles = "administrator", AuthenticationSchemes = "CookieAuthentication")]
        public async Task<IActionResult> DeleteReported(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var Offer = await _context.Offer.Include(o => o.User).Include(o => o.OfferReports).FirstOrDefaultAsync(o => o.Offerid == id);
            if (Offer == null)
            {
                return NotFound();
            }
            foreach (var report in Offer.OfferReports)
            {
                _context.OfferReport.Remove(report);
            }
            _context.Offer.Remove(Offer);
            await _context.SaveChangesAsync();
            return Ok();
        }

        [Authorize(Roles = "administrator", AuthenticationSchemes = "CookieAuthentication")]
        public async Task<IActionResult> OfferDeleted(int? id)
        {
            if (id == null)
                return RedirectToAction("ReportedOffers");

            var user = await _context.PageUser.FirstOrDefaultAsync(u => u.Userid == id);

            return View(user);
        }

        [Authorize(Roles = "administrator", AuthenticationSchemes = "CookieAuthentication")]
        [HttpPost]
        public async Task<IActionResult> BlockUser(int? id, int ReasonId)
        {
            if (id == null)
            {
                return NotFound();
            }
            var user = await _context.PageUser.FirstOrDefaultAsync(o => o.Userid == id);

            user.isBlocked = true;
            user.blockType = ReasonId;
            user.dateOfBlock = DateTime.Now;
            user.isReported = false;

            _context.Update(user);

            await _context.SaveChangesAsync();

            return RedirectToAction("ReportedOffers");
        }

        [Authorize(Roles = "administrator", AuthenticationSchemes = "CookieAuthentication")]
        public async Task<IActionResult> RejectReport(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var Offer = await _context.Offer.Include(o => o.OfferReports).FirstOrDefaultAsync(o => o.Offerid == id);
            if (Offer == null)
            {
                return NotFound();
            }
            foreach (var report in Offer.OfferReports)
            {
                report.IsActive = false;
                _context.Update(report);
            }
            Offer.IsReported = false;
            _context.Update(Offer);
            await _context.SaveChangesAsync();
            return Ok();
        }

        #endregion Admin - oferty zgłoszone

        public IActionResult Index()
        {
            return RedirectToAction(nameof(Search));
        }

        // GET: Offers
        public IActionResult Search()
        {
            ViewData["CategoryId"] = new SelectList(_context.Category, "Categoryid", "CategoryName");
            return View();
        }

        [Authorize]
        public async Task<PartialViewResult> MyOffersListPartial(int? pageNumber, string order)
        {
            if (User.Identity.Name == null) return null;
            var Offers = SortedList(order);
            string email = User.Identity.Name;
            PageUser user = _context.PageUser.FirstOrDefault(u => u.EmailAddress == email);
            if (user == null) return null;
            Offers = Offers.Where(o => o.UserId == user.Userid);
            int pageSize = 15;
            return PartialView("_MyOfferList", await PaginatedList<Offer>.CreateAsync(Offers, pageNumber ?? 1, pageSize));
        }

        public async Task<PartialViewResult> OfferListPartial(int? pageNumber, string order, string searchString, int categoryId, Filter Filter)
        {
            var Offers = SortedList(order);
            Offers = Offers.Where(o => o.ExpirationDate >= DateTime.Now);
            if (categoryId != 0)
            {
                Offers = Offers.Where(o => o.CategoryId == categoryId);
            }
            Offers = Filters(Offers, Filter);
            if (searchString != null)
            {
                searchString = searchString.TrimEnd(); // uciecie nadmiaru spacji na koncu

                var wordList = searchString.ToLower().Split(' ').ToList();
                wordList.RemoveAll(o => o == ""); //usumoecie z listy pustych strignow
                for (int i = 0; i < wordList.Count; i++) // usuwanie końcówek
                {
                    if (wordList[i].Length > 4) wordList[i] = wordList[i].Substring(0, wordList[i].Length - 2);
                }
                var words = wordList.ToArray();
                if (words.Count() >= 2) // jesli wiecej niz dwa slowa musza pasowac conajmniej  2
                {
                    Offers = Offers.Search(o => o.Title.ToLower(), o => o.Description.ToLower()).Containing(words).ToRanked().Where(o => o.Hits >= 2).Select(o => o.Item);
                }
                Offers = Offers.Search(o => o.Title, o => o.Description).Containing(words); //https://ninjanye.github.io/SearchExtensions/
            }
            int pageSize = 15; Offers = Offers.OrderByDescending(x => x.status == 1);
            return PartialView("_OfferList", await PaginatedList<Offer>.CreateAsync(Offers, pageNumber ?? 1, pageSize));
        }

        private IQueryable<Offer> Filters(IQueryable<Offer> offers, Filter filter)
        {
            var offerList = offers;
            if (filter.WageLow != null || filter.WageUp != null)
            {
                offerList = offerList.Where(o => o.Wage >= (filter.WageLow == null ? 0 : filter.WageLow) && o.Wage <= (filter.WageUp == null ? Int32.MaxValue : filter.WageUp));
            }
            if (filter.DateLow != null || filter.DateUp != null)
            {
                offerList = offerList.Where(o => o.CreationDate >= (filter.DateLow == null ? DateTime.MinValue : filter.DateLow) && o.CreationDate <= (filter.DateUp == null ? DateTime.MaxValue : filter.DateUp));
            }
            return offerList;
        }

        private IQueryable<Offer> SortedList(string order)
        {
            switch (order)
            {
                case "nameAsc":
                    return _context.Offer.Include(o => o.Category).OrderBy(o => o.Title);

                case "nameDesc":
                    return _context.Offer.Include(o => o.Category).OrderByDescending(o => o.Title);

                case "wageAsc":
                    return _context.Offer.Include(o => o.Category).OrderBy(o => o.Wage);

                case "wageDesc":
                    return _context.Offer.Include(o => o.Category).OrderByDescending(o => o.Wage);

                case "dateAsc":
                    return _context.Offer.Include(o => o.Category).OrderBy(o => o.CreationDate);

                case "dateDesc":
                    return _context.Offer.Include(o => o.Category).OrderByDescending(o => o.CreationDate);

                default:
                    return _context.Offer.Include(o => o.Category).OrderBy(o => o.Title);
            }
        }

        [Authorize]
        [HttpGet]
        public IActionResult MyOffers()
        {
            return View();
        }

        // GET: Offers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var offer = await _context.Offer
                .Include(o => o.Category)
                .Include(o => o.User)

app/Views/Offers/Confirmation.cshtml
@model IEnumerable<freelancerzy.Models.Offer>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreationDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastModificationDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ExpirationDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ViewCounter)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Wage)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.User)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreationDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastModificationDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ExpirationDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ViewCounter)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Wage)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category.CategoryName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.User.EmailAddress)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Offerid">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Offerid">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Offerid">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

app/Views/Offers/Create.cshtml
@model freelancerzy.Models.Offer

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Offer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <select asp-for="UserId" class ="form-control" asp-items="ViewBag.UserId"></select>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class ="form-control" asp-items="ViewBag.CategoryId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreationDate" class="control-label"></label>
                <input asp-for="CreationDate" class="form-control" />
                <span asp-validation-for="CreationDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastModificationDate" class="control-label"></label>
                <input asp-for="LastModificationDate" class="form-control" />
                <span asp-validation-for="LastModificationDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ExpirationDate" class="control-label"></label>
                <input asp-for="ExpirationDate" class="form-control" />
                <span asp-validation-for="ExpirationDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ViewCounter" class="control-label"></label>
                <input asp-for="ViewCounter" class="form-control" />
                <span asp-validation-for="ViewCounter" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Wage" class="control-label"></label>
                <input asp-for="Wage" class="form-control" />
                <span asp-validation-for="Wage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

app/Views/Offers/Edit.cshtml
@model freelancerzy.Models.Offer

@{
    ViewData["Title"] = "Edit";
}
<div>
    <h1 class="display-3 text-center mt-4 mb-4">Edytuj Ofertę</h1>
    <!--<p><label asp-for="LastModificationDate" class="control-label"></label> : @Model.LastModificationDate</p> -->
</div>
<div class="container bg-white border border-primary rounded" style="width:60%; padding:30px">
<form asp-action="Edit" class="form-horizontal">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Offerid" />
            <input type="hidden" asp-for="UserId" />
            <input type="hidden" asp-for="CreationDate" />
            <input type="hidden" asp-for="LastModificationDate" />
            <input type="hidden" asp-for="LastModificationDate" />
            <input type="hidden" asp-for="ViewCounter" />
            <input type="hidden" asp-for="Wage" />
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class="editSiteBackground form-control" asp-items="ViewBag.CategoryId"></select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control editSiteBackground"/>
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" rows="12" style="padding:3px; width:100%" placeholder="Opis" maxlength="1500"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ExpirationDate" class="control-label"></label>
                <input type="date" asp-for="ExpirationDate" class="form-control editSiteBackground" min=@ViewBag.minExpirationDate max=@ViewBag.maxExpirationDate/>
                <span asp-validation-for="ExpirationDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WageValue" class="control-label"></label>
                <input asp-for="WageValue" class="form-control editSiteBackground"/>
                <span asp-validation-for="WageValue" class="text-danger"></span>
            </div>
            <div class="form-group text-center">
                <input type="submit" value="Zatwierdź" style="padding:15px 40px" class="btn btn-outline-primary btn-dark text-light submitButton"/>
            </div>
        </form>
    <div>
        <a asp-area="" asp-controller="Offers" asp-action="MyOffers" class="btn btn-outline-primary btn-dark text-light submitButton">Anuluj</a>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

app/Views/Offers/NewOffer.cshtml
@model freelancerzy.Models.Offer
@{
    ViewData["Title"] = "Nowe ogłoszenie";
}

<section class="front">
    <div style="padding:20px">
        <h1 class="display-3 text-center mt-4 mb-4">Dodaj Ofertę</h1>
        <br />
    </div>
        
    <div id="content" class="container bg-white border border-primary rounded">
            <form asp-action="NewOffer" class="text-center">
                <br />
                <h3>Kategoria</h3>
                <select class="text-center" asp-for="CategoryId" asp-items="ViewBag.CategoryId" style="padding:3px; width:30%">
                </select>
                <br />
                <br />
                <div>
                    <h3>Tytuł</h3>
                    <input asp-for="Title" style="padding:3px; width:100%" placeholder="Tytuł">
                    <span asp-validation-for="Title" style="font-size: small" class="text-danger" />
                </div>
                <br />
                <br />

                <textarea asp-for="Description" rows="12" style="padding:3px; width:100%" placeholder="Opis" maxlength="1500"></textarea>
                <span asp-validation-for="Description" style="font-size: small" class="text-danger"></span>
                <br />
                <br />
                <div class="form-group">
                    <h3>@Html.DisplayNameFor(model => model.Wage)</h3>
                    <input type="text" asp-for="WageValue" style="padding: 3px; width: 30%" placeholder="@Html.DisplayNameFor(model => model.Wage) - może pozostać puste" />
                    <span asp-validation-for="WageValue" style="font-size: small" class="text-danger"></span>
                </div>
                <br />
                <br />
                <div class="text-center">
                    <input type="submit" style="padding:15px 50px;font-size:large;" class="btn btn-outline-primary btn-dark text-light" value="Dodaj" />
                </div>
                <br />
            </form>           
    </div>


</section>

<style>
    #content {
        width:60%;
        margin-right: 20%;
        margin-left: 20%;
        padding:20px;
    }
</style>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

app/Views/Offers/ReportedDetails.cshtml
@model freelancerzy.Models.Offer

@{
    ViewData["Title"] = "Szczegóły: " + Model.Title;
}
<head>
    <link href="https://code.jquery.com/ui/1.10.4/themes/ui-lightness/jquery-ui.css"
          rel="stylesheet">
</head>



<div id="content" class="row bg-white border border-primary rounded pb-3">
    <div class="col-12 mt-4 mb-3">
        <h1>@Model.Title</h1>
    </div>
    <div class="col-lg-9 pr-4">
        Dodał:
        <h4>@Model.User.FirstName - @Model.User.EmailAddress</h4>
        <article>
            <div class="mt-3 text-justify">
                <h2>Szerszy opis usługi</h2>
                <div class="mt-3 mb-3">@Model.Description</div>
            </div>
        </article>
    </div>
    <div class="col-lg-3 mb-5">
        <div style="background-color:lightgray" class="p-3  border border-dark rounded">
            <h5>Szczegóły:</h5>
            @if (Model.Wage == null)
            {
                <div>Stawka: <b>nieokreślona</b></div>
            }
            else
            {
                <div>Stawka: <b>@Model.Wage zł</b></div>
            }
            <div>Kategoria: <b>@Model.Category.CategoryName</b></div>
            <br />
            <h5>Dana kontaktowe:</h5>
            <div>Imię: <b>@Model.User.FirstName</b></div>
            <div>Email: <b>@Model.User.EmailAddress</b></div>
            <div>Numer telefonu: <b>@Model.User.Phonenumber</b></div>

        </div>
    </div>
    <div class="reportDecision">
        <h3 style="color:red;">Zdecyduj, co zrobić z tą ofertą</h3>
        <div class="reportDecisionButtons">
            <button id="cancelBtn" class="btn btn-outline-primary btn-dark">Pozostaw</button>
            <button id="deleteBtn" class="btn btn-outline-primary btn-dark">Usuń</button>
        </div>
        <div id="dialog-1" title="Czy na pewno chcesz usunąć ofertę?">

        </div>
        <div id="dialog-2"
             title="Czy na pewno chcesz pozostawić ofertę?"></div>
    </div>
    <div id="buttons" class="col-12">
        Dodano: <b>@Model.CreationDate</b>, Liczba wyświetleń: @Model.ViewCounter
        <br /><br />
    </div>
    <h2 class="m-2">Zgłoszenia: </h2>
    @foreach(var report in Model.OfferReports)
    {
        <div class="col-12 border rounded border-dark mb-2">
            <dl class="row">
                <dt class="col-2">
                    Powód:
                </dt>
                <dd class="col-10">
                    @report.OfferReportReason.Description
                </dd>
                <dt class="col-2">
                    Data:
                </dt>
                <dd class="col-10">
                    @report.ReportDate
                </dd>
            </dl>
        </div>
    }
    <a class="btn btn-outline-primary btn-dark m-2" href='javascript:history.go(-1)'>Powrót</a>
</div>


<style>
    #content {
        margin: 10%;
        margin-top: 5%;
    }

    .reportDecision {
        margin-left: auto;
        margin-right: auto;
        display: flex;
        flex-direction: column;
    }

    .reportDecisionButtons {
        margin: auto;
    }
</style>
<script>

    const id = @Model.Offerid;

    const DeleteOffer = (id) => {
        $.ajax({
            method: "DELETE",
            url: "/Offers/DeleteReported?id=" + id,
            cache: false

        }
        ).fail(() => alert("Błąd podczas usuwania oferty"))
            .done(() => {
                const url = '@Url.Action("OfferDeleted","Offers",new { id= Model.UserId})';
                window.location.href = url;
            })
    }

    const RejectReport = (id) => {
         $.ajax({
            method: "GET",
            url: "/Offers/RejectReport?id=" + id,
            cache: false

        }
        ).fail(() => alert("Błąd podczas przetwarzania rządania"))
            .done(() => {
                const url = '@Url.Action("ReportedOffers","Offers")';
                window.location.href = url;
            })
    }

    $(function () {
        $('#dialog-1').dialog({
            autoOpen: false,
            modal: true,
            dialogClass: 'border border-dark rounded',
            width: 500,
            show: 'fold',
            hide: 'fold',
            resizable: false,
            closeText: 'Zamknij',
            draggable:false,
            buttons: {
                TAK: function () {
                    DeleteOffer(id);
                },
                NIE: function () {
                    $(this).dialog('close');
                }
            }

        });

        $('#dialog-2').dialog({
            autoOpen: false,
            modal: true,
            dialogClass: 'border border-dark rounded',
            width: 550,
            show: 'fold',
            hide: 'fold',
            resizable: false,
            closeText: 'Zamknij',
            draggable: false,
            buttons: {
                TAK: function () {
                    RejectReport(id);
                },
                NIE: function () {
                    $(this).dialog('close');
                }
            }

        });
        $('#deleteBtn').click(function () {
            $('#dialog-1').dialog("open");
        });


        $('#cancelBtn').click(function () {
            $('#dialog-2').dialog("open");
        });
    });
</script>
@section scripts{
    <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
    <script src="https://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
}
<style>
    .ui-widget-header, .ui-state-default, ui-button {
        background-color:dimgrey;
        color: black;
        font-weight: bold;
    }
    .ui-dialog {
        padding: 10px;
        background: lightgray;
    }
    
</style>

app/Views/Offers/_OfferList.cshtml
@model freelancerzy.Models.PaginatedList<freelancerzy.Models.Offer>

@{
    var reportConfirmation = false;
    var confirmation = false;
}

@foreach (var offer in Model)
{
    <div id="text" class="m-1 border rounded border-dark offer" style="padding-bottom: 0px">
        <table class="table table-borderless pb-2" style="border:none; margin-bottom: 0px">
            <tbody>
                <tr>
                    <td width="70%">
                        <h4 class="p-1">
                            @offer.Title
                            @if (offer.status == 1)
                            {
                                <a href="@Url.Action("Static","Offers",  new { name = "Promote" } )" id="btn" class="btn btn-primary">Oferta Promowana</a>
                            }
                        </h4>
                    </td>
                    <td width="30%" class="text-center">
                        @if (offer.Wage != null)
                        {
                            <h4>@Html.DisplayFor(modelItem => offer.Wage)</h4>
                        }
                        else
                        {
                            <h4>Nieokreślona stawka</h4>
                        }
                    </td>
                </tr>
                <tr>
                    <td width="70%" class="mb-0 pb-0">

                        @if (offer.Description?.Length > 300)
                        {
                            <p class="p-1">@offer.Description.Substring(0, 300)...</p>
                        }
                        else
                        {
                            <p class="p-1">@offer.Description</p>
                        }
                    </td>
                    <td class="text-center align-bottom">
                        <a id="btn" class="btn btn-dark btn-outline-primary" asp-action="Details" asp-route-id="@offer.Offerid">Szczegóły</a>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
}

@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<div>
    <div style="width:50%" class="d-inline-block ">
        Jesteś na stronie: <input min="1" max="@Model.TotalPages" type="number" value="@Model.PageIndex" id="page" style="width:50px;" /> z @Model.TotalPages <button class="btn btn-default" id="goToPage">Przejdź</button>
    </div>
    <div style="float:right">
        <button id="prev"
                class="btn btn-default" @prevDisabled>
            Poprzednia
        </button>
        <button id="next"
                class="btn btn-default" @nextDisabled>
            Następna
        </button>
    </div>
</div>
<script>
    var totalPages = @Model.TotalPages;
</script>
<style>
    div#text > table:hover {
        color: ghostwhite !important;
    }
</style>